version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: invest-tracker-mongodb
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=invest-tracker
    networks:
      - app-network

  server:
    build: ./server
    container_name: invest-tracker-server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
